# -*- coding: utf-8 -*-
"""GCS_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EaFyRHRjmord5qTaLDQMeKsebR93WSbP
"""

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np
from tqdm import tqdm
import os
import seaborn as sns
from pathlib import Path
#---------------- Load the GCS cohort------------------------

current = Path(__file__).resolve()
GCS_ROOT = None
for parent in current.parents:
    if parent.name == "GCS":
        GCS_ROOT = parent
        break

if GCS_ROOT is None:
    raise RuntimeError("GCS folder not found")

metadata_s0001_path = GCS_ROOT / "Cohort" / "GCS_MGH_HarvardEEG_metadata.csv"
metadata_s0002_path = GCS_ROOT / "Cohort" / "GCS_BWH_HarvardEEG_metadata.csv"

df_s0001=pd.read_csv(metadata_s0001_path)
df_s0002=pd.read_csv(metadata_s0002_path)


GCS_EEG_all_df_censor_mgb=pd.concat([df_s0002, df_s0001], ignore_index=True)
subs_GCS=GCS_EEG_all_df_censor_mgb['BDSPPatientID'].unique()

GCS_EEG_all_df_censor_mgb=GCS_EEG_all_df_censor_mgb.drop(columns=['DateOfBirth',    'DateOfDeath',  'CensorDate',
                                                                    'HospitalAdmitDTS', 'HospitalDischargeDTS',
                                                                    'AgeAtVisit',   'PatientRace', 'EthnicGroupDSC', 'SexDSC'])

df = GCS_EEG_all_df_censor_mgb.copy()

idx = (
    df.groupby(['BDSPPatientID', 'SessionID'])['DurationInSeconds']
      .max()
      .reset_index()
      .sort_values(['BDSPPatientID', 'DurationInSeconds'], ascending=[True, False])
      .drop_duplicates(subset=['BDSPPatientID'])
      [['BDSPPatientID', 'SessionID']]
)

df_filtered = df.merge(idx, on=['BDSPPatientID', 'SessionID'], how='inner')

#-------------------- Sorting subjects based GCS burden -------------------
# Copy dataframe
df_gcs = df_filtered.copy()
df_gcs['GCS'] = df_gcs['R CPN GLASGOW COMA SCALE SCORE']

# Compute session-level GCS burden (15 - GCS; low GCS = high burden)
df_gcs['GCS_burden'] = 15 - df_gcs['GCS']

# If all rows in a session have same duration, simple mean is enough
session_burden = (
    df_gcs.groupby(['BDSPPatientID', 'SessionID'])['GCS_burden']
    .mean()
    .reset_index()
)

# Patient-level GCS burden (take max across sessions)
patient_burden = (
    session_burden.groupby('BDSPPatientID')['GCS_burden']
    .max()
    .reset_index()
    .sort_values('GCS_burden', ascending=False)
)

# Keep patients in descending burden order
sorted_pids = patient_burden['BDSPPatientID'].values
df_gcs_sorted = pd.merge(
    df_gcs,
    patient_burden[['BDSPPatientID']],
    on='BDSPPatientID',
    how='inner'
)
df_gcs_sorted = df_gcs_sorted.set_index('BDSPPatientID').loc[sorted_pids].reset_index()

df_gcs_sorted = df_gcs_sorted[
    df_gcs_sorted['R CPN GLASGOW COMA SCALE SCORE'].notna()
]

# Group by patient and get number of unique BidsFolder and SessionID combinations
check = df_gcs_sorted.groupby('BDSPPatientID').agg({
    'BidsFolder': 'nunique',
    'SessionID': 'nunique'
})

# Show any patients where there is more than one BidsFolder or SessionID
violations = check[(check['BidsFolder'] > 1) | (check['SessionID'] > 1)]
# print("Patients with inconsistent mapping:")
# print(violations)

if violations.empty:
    print("✅ All BDSPPatientID values have exactly one unique BidsFolder and SessionID.")
else:
    print(f"⚠ Found {len(violations)} patients with inconsistent mapping.")

#-------------- Just consider one particular BIDS folder for these patients ----------------------
# First, for each patient, find the most common BidsFolder (or just the first one)
patient_folder_gcs = df_gcs_sorted.groupby('BDSPPatientID')['BidsFolder'] \
                          .agg(lambda x: x.mode()[0])  # mode gives the most frequent

# Merge back to keep only rows with that BidsFolder
df_gcs_filtered_bids = df_gcs_sorted.merge(patient_folder_gcs.rename('ChosenBidsFolder'),
                              on='BDSPPatientID')

df_gcs_filtered_bids = df_gcs_filtered_bids[df_gcs_filtered_bids['BidsFolder'] == df_gcs_filtered_bids['ChosenBidsFolder']].copy()

# Drop the helper column if you want
df_gcs_filtered_bids.drop(columns='ChosenBidsFolder', inplace=True)

# Verify that each patient now has only one unique BidsFolder
check = df_gcs_filtered_bids.groupby('BDSPPatientID')['BidsFolder'].nunique()
print(check[check > 1])  # should be empty



# ------------- Generate the GCS recording hour column and EEG duration in hour column ------------------------------
# Ensure datetime columns
df_gcs_filtered_bids['GCSRecordedDTS'] = pd.to_datetime(df_gcs_filtered_bids['GCSRecordedDTS'])
df_gcs_filtered_bids['EEGBeginDTS'] = pd.to_datetime(df_gcs_filtered_bids['EEGBeginDTS'])

# EEG duration in minutes
df_gcs_filtered_bids['EEGDurationInHour'] = df_gcs_filtered_bids['DurationInSeconds'] / 3600

# GCS timing in minutes relative to EEG start
df_gcs_filtered_bids['GCSHour'] = (df_gcs_filtered_bids['GCSRecordedDTS'] - df_gcs_filtered_bids['EEGBeginDTS']).dt.total_seconds() / 3600

#-------------- GCS Consort Diagram with log time scale -------------------

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.size'] = 6
plt.rcParams['font.weight'] = 'bold'

plt.rcParams['axes.labelweight'] = 'bold'
plt.rcParams['axes.titleweight'] = 'bold'

plt.rcParams['xtick.labelsize'] = 6
plt.rcParams['ytick.labelsize'] = 6
# ---------- Data Preparation ----------
df_full = df_gcs_filtered_bids.copy().dropna(subset=['EEGDurationInHour', 'GCSHour', 'GCS'])
df_full = df_full[df_full['GCSHour'] <= 30]

unique_pids = df_full['BDSPPatientID'].unique()
pid_to_y = {pid: i for i, pid in enumerate(unique_pids)}
df_full['y_coord'] = df_full['BDSPPatientID'].map(pid_to_y)

# ---------- Color map for GCS ----------
GCS_levels = np.arange(3, 16)
base_cmap = plt.cm.magma
colors = base_cmap(np.linspace(0.15, 0.95, len(GCS_levels)))
cmap = mcolors.ListedColormap(colors)
norm = mcolors.BoundaryNorm(np.arange(2.5, 16.5, 1), cmap.N)

# ---------- Figure ----------
fig, ax = plt.subplots(figsize=(7, 6), dpi=200)

# We set epsilon to be just before 1 minute so the 1-min tick shows up nicely
epsilon = 0.005  # ~18 seconds

# 1. Background Duration Lines
duration_df = df_full.groupby('y_coord')['EEGDurationInHour'].max().reset_index()
ax.hlines(
    y=duration_df['y_coord'],
    xmin=epsilon,
    xmax=duration_df['EEGDurationInHour'].clip(upper=30),
    color='lightgray',
    linewidth=0.4,
    alpha=0.2,
    zorder=1
)

# 2. GCS Points
# Shift values < epsilon to epsilon for log display
x_coords = np.where(df_full['GCSHour'] < epsilon, epsilon, df_full['GCSHour'])

ax.scatter(
    x_coords,
    df_full['y_coord'],
    c=df_full['GCS'],
    cmap=cmap,
    norm=norm,
    s=3,         # Tiny points to prevent vertical overlap
    alpha=0.8,
    edgecolors='none',
    zorder=2,
    rasterized=True
)

# ---------- Log Scale & Custom Ticks ----------
ax.set_xscale('log')

# Define ticks by converting minutes to hours
# 1m, 6m, 10m, 1h, 5h, 10h, 20h, 30h
tick_hours = [1/60, 10/60, 30/60,1.0, 5.0, 10.0, 20.0, 30.0]
tick_labels = ['1m', '10m', '30m','1h', '5h', '10h', '20h', '30h']

ax.set_xlim(epsilon, 30)
ax.set_xticks(tick_hours)
ax.set_xticklabels(tick_labels)

# Minor ticks to help guide the eye across log spans
ax.grid(True, which='major', axis='x', linestyle='--', alpha=0.4)

ax.set_xlabel("Time since EEG start (Log Scale: Minutes to Hours)")
ax.set_ylabel(f" No. of Patients")
ax.set_title("Swimmer Plot (0-30 Hours): GCS Assessments")
ax.set_ylim(len(unique_pids), 0)
ax.invert_yaxis()
ax.margins(y=0)
# ---------- Colorbar ----------
sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
cbar = plt.colorbar(sm, ax=ax, label="GCS Level", shrink=0.5, pad=0.02)
cbar.set_ticks(GCS_levels)
plt.tight_layout()
plt.show()

#-------------- GCS Consort Diagram with linear time scale -------------------
# ---------- Preprocess once ----------
df_plot = df_gcs_sorted.copy()

for col in ['EEGBeginDTS', 'EEGExamEndDTS', 'GCSRecordedDTS']:
    df_plot[col] = pd.to_datetime(df_plot[col], errors='coerce')

df_plot['GCS'] = df_plot['R CPN GLASGOW COMA SCALE SCORE']

patient_groups = dict(tuple(df_plot.groupby('BDSPPatientID')))
unique_pids = df_plot['BDSPPatientID'].dropna().unique()

# ---------- Figure ----------
fig, ax = plt.subplots(figsize=(6, 5), dpi=200)

gcs_levels = np.arange(3, 16)  # 3 to 15 inclusive

base_cmap = plt.cm.magma
colors = base_cmap(np.linspace(0.15, 0.95, len(gcs_levels)))
cmap = mcolors.ListedColormap(colors)
norm = mcolors.BoundaryNorm(np.arange(2.5, 16.5, 1), cmap.N)

patient_spacing = 0.2
session_spacing = 0.3

plt.rcParams['font.family'] = 'serif'
plt.rcParams['font.size'] = 6
plt.rcParams['font.weight'] = 'bold'
plt.rcParams['axes.labelweight'] = 'bold'
plt.rcParams['axes.titlesize'] = 6
plt.rcParams['axes.titleweight'] = 'bold'
plt.rcParams['xtick.labelsize'] = 6
plt.rcParams['ytick.labelsize'] = 6

# ---------- Plot ----------
for i, pid in enumerate(tqdm(unique_pids, desc="Processing patients"), start=1):

    df_patient = patient_groups.get(pid)
    if df_patient is None:
        continue

    pairs = (
        df_patient[['BidsFolder', 'SessionID']]
        .dropna()
        .drop_duplicates()
        .sort_values(['BidsFolder', 'SessionID'])
        .itertuples(index=False)
    )

    patient_y = i * patient_spacing

    for j, (bids, sess) in enumerate(pairs):
        y_val = patient_y + (j - 0.5) * session_spacing

        sess_df = df_patient[
            (df_patient['BidsFolder'] == bids) &
            (df_patient['SessionID'] == sess)
        ]

        start = sess_df['EEGBeginDTS'].iloc[0]
        end   = sess_df['EEGExamEndDTS'].iloc[0]
        if pd.isna(start) or pd.isna(end):
            continue

        duration_hr = (end - start).total_seconds() / 3600
        ax.hlines(y_val, 0, duration_hr, color='lightgray', linewidth=2.5, alpha=0.8)

        gcs_df = sess_df.dropna(subset=['GCSRecordedDTS', 'GCS'])
        if gcs_df.empty:
            continue

        x = (gcs_df['GCSRecordedDTS'] - start).dt.total_seconds().values / 3600
        y = np.full_like(x, y_val, dtype=float)
        c = gcs_df['GCS'].values

        ax.scatter(
            x, y,
            c=c,
            cmap=cmap,
            norm=norm,
            s=1,
            alpha=0.9,
            edgecolors='none',
            zorder=3,
            rasterized=True
        )

# ---------- Axes ----------
ax.set_xlabel("Time since EEG start (Hours)")
ax.set_ylabel(f"No. of unique patients")
ax.set_title("Swimmer Plot (0–30 Hours): GCS Assessments")

tick_interval = 500
ytick_indices = [1] + list(range(tick_interval, len(unique_pids) + 1, tick_interval))
yticks = [i * patient_spacing for i in ytick_indices]
ax.set_yticks(yticks)
ax.set_yticklabels([str(i) for i in ytick_indices])

ax.set_xlim(0, 30)
ax.margins(x=0, y=0)
ax.set_xticks(np.arange(0, 31, 1))
ax.set_xticklabels([f"{i}h" for i in range(31)], rotation=45)

ax.set_xticks(np.arange(0, 30.5, 0.5), minor=True)
ax.tick_params(axis='x', which='minor', length=3)

ax.grid(True, which='major', axis='x', linestyle='--', alpha=0.4)

# ---------- Colorbar ----------
sm = plt.cm.ScalarMappable(cmap=cmap, norm=norm)
sm.set_array([])
cbar = plt.colorbar(sm, ax=ax, label="GCS Level", fraction=0.046, pad=0.04, shrink=0.7)
cbar.set_ticks(gcs_levels)
cbar.set_ticklabels(gcs_levels)

plt.tight_layout()
plt.show()