# build_i0002_master_exposure.py
"""
Master per-EEG exposure file for the I0002 GCS cohort.

For patients with NO medication administration records in I0002_PIVOTED_MEDS_PATCHED_PARQUET,
exposure columns are set to NA (not 0). "No exposure observed" and
"no data available" are different things.

Schema matches I0001 master file (14 exposure columns total). I0002-specific
infusion columns are all 0 by cohort characteristic (no sedative or systemic
opiate infusions in this cohort).
"""

import duckdb
import pandas as pd

import med_config

try:
    import winsound
    HAS_WINSOUND = True
except ImportError:
    HAS_WINSOUND = False


WINDOW_HOURS = 24
EEG_TIMESTAMP_COL = "RecordedDTS"

BENZO_DRUGS  = ["lorazepam", "diazepam", "midazolam", "other_benzo"]
OPIATE_DRUGS = ["fentanyl", "morphine", "hydromorphone"]


def norm_id(s):
    return (
        s.astype(str).str.strip()
         .str.replace(r"\.0$", "", regex=True)
         .replace({"nan": None, "None": None, "": None})
    )


def get_patients_with_med_data(cohort_meds_parquet):
    con = duckdb.connect()
    parquet_str = str(cohort_meds_parquet).replace("\\", "/")
    df = con.execute(f"""
        SELECT DISTINCT CAST(BDSPPatientID AS VARCHAR) AS pid
        FROM '{parquet_str}'
    """).df()
    con.close()
    return set(norm_id(df["pid"]).dropna())


def apply_na_mask(eeg_df, exposure_series, patients_with_med_data):
    has_data = eeg_df["BDSPPatientID"].isin(patients_with_med_data)
    result = exposure_series.astype("Int64")
    result[~has_data] = pd.NA
    return result


def _exposure_via_duckdb(eeg_df, admins_df, patients_with_med_data):
    con = duckdb.connect()
    eeg_slice = eeg_df[["_row_id", "BDSPPatientID", "_eeg_ts", "_window_start"]].copy()
    eeg_slice["BDSPPatientID"] = eeg_slice["BDSPPatientID"].astype(str)
    adm = admins_df.copy()
    adm["BDSPPatientID"] = adm["BDSPPatientID"].astype(str)
    con.register("eegs", eeg_slice)
    con.register("adm", adm)
    result = con.execute("""
        SELECT e._row_id,
               MAX(CASE WHEN adm._med_ts BETWEEN e._window_start AND e._eeg_ts THEN 1 ELSE 0 END) AS exposure
        FROM eegs e
        LEFT JOIN adm ON e.BDSPPatientID = adm.BDSPPatientID
                     AND adm._med_ts >= e._window_start
                     AND adm._med_ts <= e._eeg_ts
        GROUP BY e._row_id
    """).df()
    con.close()
    m = dict(zip(result["_row_id"], result["exposure"]))
    series = eeg_df["_row_id"].map(m).fillna(0).astype(int)
    return apply_na_mask(eeg_df, series, patients_with_med_data)


def load_bolus_timestamps(drug_list, bucket):
    frames = []
    for drug in drug_list:
        path = med_config.I0002_BOLUS_EXPOSURE_DIR / f"{drug}_boluses_{bucket}.csv"
        if path.exists():
            frames.append(pd.read_csv(path, usecols=["BDSPPatientID", "TakenTime"]))
    if not frames:
        return pd.DataFrame(columns=["BDSPPatientID", "_med_ts"])
    admins = pd.concat(frames, ignore_index=True)
    admins["BDSPPatientID"] = norm_id(admins["BDSPPatientID"])
    admins["_med_ts"] = pd.to_datetime(admins["TakenTime"], errors="coerce")
    admins = admins[admins["BDSPPatientID"].notna() & admins["_med_ts"].notna()]
    return admins[["BDSPPatientID", "_med_ts"]]


def compute_exposure(eeg_df, admins_df, patients_with_med_data):
    if len(admins_df) == 0:
        series = pd.Series(0, index=eeg_df.index, dtype="Int64")
        return apply_na_mask(eeg_df, series, patients_with_med_data)
    return _exposure_via_duckdb(eeg_df, admins_df, patients_with_med_data)


def main():
    try:
        patients_with_med_data = get_patients_with_med_data(
            med_config.I0002_PIVOTED_MEDS_PATCHED_PARQUET
        )
        print(f"Patients with med data: {len(patients_with_med_data):,}")

        # Load I0002 metadata
        meta = pd.read_csv(med_config.I0002_GCS_METADATA_CSV, low_memory=False)
        print(f"\nI0002 GCS EEG rows: {len(meta):,}")
        if EEG_TIMESTAMP_COL not in meta.columns:
            raise ValueError(f"'{EEG_TIMESTAMP_COL}' not found.")
        meta["BDSPPatientID"] = norm_id(meta["BDSPPatientID"])
        meta["_eeg_ts"] = pd.to_datetime(meta[EEG_TIMESTAMP_COL], errors="coerce")
        meta["_window_start"] = meta["_eeg_ts"] - pd.Timedelta(hours=WINDOW_HOURS)
        meta["_row_id"] = range(len(meta))

        # Pull ASM/antipsych from earlier output (these already need NA-masking
        # since they were generated by build_i0002_asm_antipsych_exposure)
        asm_path = med_config.I0002_ASM_ANTIPSYCH_DIR / "i0002_per_eeg_asm_antipsych_exposure.csv"
        asm = pd.read_csv(asm_path, low_memory=False)
        asm["BDSPPatientID"] = norm_id(asm["BDSPPatientID"])
        asm["_eeg_ts"] = pd.to_datetime(asm[EEG_TIMESTAMP_COL], errors="coerce")
        asm_slim = asm[["BDSPPatientID", "_eeg_ts", "LongActingASM_Exposure", "Antipsychotic_Exposure"]] \
            .drop_duplicates(subset=["BDSPPatientID", "_eeg_ts"], keep="first")
        meta = meta.merge(asm_slim, on=["BDSPPatientID", "_eeg_ts"], how="left")
        for col in ["LongActingASM_Exposure", "Antipsychotic_Exposure"]:
            meta[col] = meta[col].astype("Int64")
            meta.loc[~meta["BDSPPatientID"].isin(patients_with_med_data), col] = pd.NA

        # Benzo boluses
        print("\nComputing FastActing_Benzo_Exposure...")
        benzo_iv = load_bolus_timestamps(BENZO_DRUGS, "iv")
        meta["FastActing_Benzo_Exposure"] = compute_exposure(meta, benzo_iv, patients_with_med_data)
        n_pts = meta.loc[meta["FastActing_Benzo_Exposure"] == 1, "BDSPPatientID"].nunique()
        print(f"  Patients exposed: {n_pts:,}")

        print("\nComputing SlowActing_Benzo_Exposure...")
        benzo_non = load_bolus_timestamps(BENZO_DRUGS, "non_iv")
        meta["SlowActing_Benzo_Exposure"] = compute_exposure(meta, benzo_non, patients_with_med_data)
        n_pts = meta.loc[meta["SlowActing_Benzo_Exposure"] == 1, "BDSPPatientID"].nunique()
        print(f"  Patients exposed: {n_pts:,}")

        # Propofol bolus
        print("\nComputing Propofol_Exposure...")
        prop = load_bolus_timestamps(["propofol"], "iv")
        prop_non = load_bolus_timestamps(["propofol"], "non_iv")
        prop_all = pd.concat([prop, prop_non], ignore_index=True)
        meta["Propofol_Exposure"] = compute_exposure(meta, prop_all, patients_with_med_data)
        n_pts = meta.loc[meta["Propofol_Exposure"] == 1, "BDSPPatientID"].nunique()
        print(f"  Patients exposed: {n_pts:,}")

        # Opiate boluses
        print("\nComputing FastActing_Opiate_Exposure...")
        opi_iv = load_bolus_timestamps(OPIATE_DRUGS, "iv")
        meta["FastActing_Opiate_Exposure"] = compute_exposure(meta, opi_iv, patients_with_med_data)
        n_pts = meta.loc[meta["FastActing_Opiate_Exposure"] == 1, "BDSPPatientID"].nunique()
        print(f"  Patients exposed: {n_pts:,}")

        print("\nComputing SlowActing_Opiate_Exposure...")
        opi_non = load_bolus_timestamps(OPIATE_DRUGS, "non_iv")
        meta["SlowActing_Opiate_Exposure"] = compute_exposure(meta, opi_non, patients_with_med_data)
        n_pts = meta.loc[meta["SlowActing_Opiate_Exposure"] == 1, "BDSPPatientID"].nunique()
        print(f"  Patients exposed: {n_pts:,}")

        # ── Infusion columns (all 0 for I0002 by cohort characteristic, but
        # still NA for patients without med data) ────────────────────────────
        for col in [
            "Propofol_Infusion_Exposure",
            "Midazolam_Infusion_Exposure",
            "Ketamine_Infusion_Exposure",
            "Dexmedetomidine_Infusion_Exposure",
            "Fentanyl_Infusion_Exposure",
            "Morphine_Infusion_Exposure",
            "Hydromorphone_Infusion_Exposure",
        ]:
            series = pd.Series(0, index=meta.index, dtype="Int64")
            meta[col] = apply_na_mask(meta, series, patients_with_med_data)

        # ── Summary ──────────────────────────────────────────────────────────
        flag_cols = [
            "LongActingASM_Exposure", "Antipsychotic_Exposure",
            "FastActing_Benzo_Exposure", "SlowActing_Benzo_Exposure",
            "Propofol_Exposure",
            "FastActing_Opiate_Exposure", "SlowActing_Opiate_Exposure",
            "Propofol_Infusion_Exposure",
            "Midazolam_Infusion_Exposure",
            "Ketamine_Infusion_Exposure",
            "Dexmedetomidine_Infusion_Exposure",
            "Fentanyl_Infusion_Exposure",
            "Morphine_Infusion_Exposure",
            "Hydromorphone_Infusion_Exposure",
        ]
        eligible_mask = meta["BDSPPatientID"].isin(patients_with_med_data)
        n_eegs_eligible = int(eligible_mask.sum())
        n_pts_eligible = meta.loc[eligible_mask, "BDSPPatientID"].nunique()
        n_eegs_excluded = int((~eligible_mask).sum())
        n_pts_excluded = meta.loc[~eligible_mask, "BDSPPatientID"].nunique()
        print("\n=== Summary ===")
        print(f"  Total EEG rows: {len(meta):,}")
        print(f"  EEGs eligible (patient has med data):    {n_eegs_eligible:,}")
        print(f"  EEGs not eligible (no med data, all NA): {n_eegs_excluded:,} "
              f"from {n_pts_excluded:,} patients")
        for col in flag_cols:
            n_e = int((meta[col] == 1).sum())
            n_p = meta.loc[meta[col] == 1, "BDSPPatientID"].nunique()
            pct_e = 100 * n_e / n_eegs_eligible if n_eegs_eligible else 0
            pct_p = 100 * n_p / n_pts_eligible if n_pts_eligible else 0
            print(f"  {col:<35}  EEGs: {n_e:>6,} ({pct_e:.1f}%)  "
                  f"Patients: {n_p:>5,} ({pct_p:.1f}%)")

        out = meta.drop(columns=["_row_id", "_eeg_ts", "_window_start"])
        out_path = med_config.I0002_ASM_ANTIPSYCH_DIR / "i0002_per_eeg_master_exposure.csv"
        out.to_csv(out_path, index=False)
        print(f"\nSaved: {out_path}")

        print("\nDone.")
        if HAS_WINSOUND:
            winsound.MessageBeep(winsound.MB_OK)
        else:
            try:
                print("\a")
            except Exception:
                pass

    except Exception as e:
        print(f"\nERROR: {e}")
        if HAS_WINSOUND:
            winsound.MessageBeep(winsound.MB_ICONHAND)
        else:
            try:
                print("\a")
            except Exception:
                pass
        raise


if __name__ == "__main__":
    main()